default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: staffsearch_development
test:
  <<: *default
  database: staffsearch_test

production:
  <<: *default
  database: staffsearch_production
  username: staffsearch
  password: <%= ENV['staffsearch_DATABASE_PASSWORD'] %>